# Book settings
title: Especialidade MultiVendas
author: Eduardo Carísio
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

html:
  extra_navbar: ''

parse:
  myst_extended_syntax: true